### ISSUE TITLE
my problem

### ISSUE THREAD

**Issue by ddy-ddy** [FudanSELab/funcverbnet#22]
* FuncVerbNet version:0.1.8
* Python version:3.7
* Operating System:mac os

### Description
Hello author.
      I want to know how to use this tool to obtain the phase patters of a functionality description sentence.
e.g.,input:"Compares this string to the specified object"
       output:the phase patters of the sentence:"V {patient} to {co-patient}"
      Thank you so much.

Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by liumingwei94** [comment]
你好，目前新的版本已经加入了短语解析的功能，可以尝试一下
