### ISSUE TITLE
Phrase Pattern Identification.

### ISSUE THREAD

**Issue by ddy-ddy** [FudanSELab/funcverbnet#24]
* FuncVerbNet version:
* Python version:
* Operating System:

### Description
作者您好，看了你您们的论文之后，我备受启发。最近我正在尝试完全复现您们的论文。在论文的4.2.2小结中，您们提到了如何进行phrase pattern的识别。我对这一句话的实现比较疑惑：”The replacement is done by recursively visiting the subtree of the core clause.“。想请教一下您们，该如何递归的访问子树，然后针对5个rules进行 syntactic components的替换呢？
打扰您们了。

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by liumingwei94** [comment]
Spacy的依赖解析功能能将一个句子表示成一棵树，里面的节点是句子里面的每个词和它们之间的关系。这里的递归可能大体意思是从主句的ROOT为开始（可以视为一个以ROOT为根的子树），去访问其左子树、根节点、右子树，将其分别得到表示，最后汇集起来，得到整个子树的表示。左子树、根、右子树的表示又是通过递归方式去获得的，然后结合各种规则和节点的POS和节点之间的关系来判断每个子树的成分，比如一个子树只有名词或者是形容词+名词，那么就是NP。一个节点是动词就是V，一个节点的子树有完整的主语谓语宾语那么就是句子S之类。

**Comment by ddy-ddy** [comment]
十分感谢您的回复。您提供的方法我之前有尝试过，但是在实现的过程中遇到这么几个问题：

例子1：compares two character objects numerically.
按照我目前的理解，compares是V，two character objects是NP，但是numerically我不知道该如何划分，根据spacy的依存分析的结果来看，numerically和objects之间存在”advmod“的依存关系。我是应该把numerically划分为NP的成分还是其他成分呢？
![截屏2022-01-15 下午5 38 43](https://user-images.githubusercontent.com/58058861/149617185-245f62b8-6859-4434-aed4-9923c75a39d5.png)

例子2：Compares the specified object with this set for equality.
按照我的划分，似乎可以划分成 ”V NP with NP for NP“，然后我对应到compare这类功能性动词上去时，发现找不到适合的p_pattern.按照我的理解是否可以是这种模式：”V {patient} against/with/to {co-patient} for {theme}“，但是在p_pattern中似乎没有这种pattern。【可能是我自己的理解出了问题，导致划分错误，特向作者你请教一下😁】
![截屏2022-01-15 下午5 48 58](https://user-images.githubusercontent.com/58058861/149617511-ce489abd-8d19-4f3a-b20e-b9b09ff37194.png)

再次感谢作者的回复。

**Comment by liumingwei94** [comment]
1. numerically这种修饰性的副词在递归子树的时候可以忽略掉。
2. ”V NP with NP for NP“ 对，从句子本身来说是这样。然后会和”V {patient} against/with/to {co-patient}“进行匹配。和模式匹配是找最接近的，因为我们没办法保证我们的模式覆盖率100%。

**Comment by ddy-ddy** [comment]
> 
了解了，十分感谢您的解答。😁

**Comment by liumingwei94** [comment]
我们更新的版本加入了短语解析功能，可以尝试使用一下。

**Comment by ddy-ddy** [comment]
好的👌迫不及待了嘻嘻嘻> 我们更新的版本加入了短语解析功能，可以尝试使用一下。
